In [1]:
import os
import json
import numpy as np

import bids
from bids import BIDSLayout

import nibabel as nib

from nilearn import plotting
import matplotlib.pyplot as plt

In [2]:
project_dir = os.path.join('/Users/KRS228/data/', 'FLT_decoding/')
deriv_dir = os.path.join(project_dir, 'derivatives')
mask_dir = os.path.join(project_dir, 'masks')
trial_map_dir = os.path.join(project_dir, 'trial_models')

## Decoding

In [3]:
from glob import glob

from nilearn.decoding import Decoder
from nilearn.input_data import NiftiMasker

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/nilearn/input_data/__init__.py:27: FutureWarning: The import path 'nilearn.input_data' is deprecated in version 0.9. Importing from 'nilearn.input_data' will be possible at least until release 0.13.0. Please import from 'nilearn.maskers' instead.
  warnings.warn(message, FutureWarning)


In [4]:
task_id = 'tonecat'
sub_id = 'FLT01'
fwhm_sub = 1.5
space_label = 'T1w' #'MNI152NLin2009cAsym' 

In [5]:
z_maps = sorted(glob(trial_map_dir+'/run*/*di*nii.gz'))
print('# of z-maps: ', len(z_maps))

#conditions = stim_list * len(imgs)
#conditions = [os.path.basename(x)[68:74] for x in z_maps] # for MNI directory
conditions = [os.path.basename(x)[52:58] for x in z_maps] # for T1w directory
print('# of conditions: ', len(conditions))

print(conditions[:10])

print('unique # of conditions = ', np.unique(conditions).shape)

conditions_tone = [stim[:3] for stim in conditions]
print(conditions_tone[:10])

conditions_talker = [stim[4:6] for stim in conditions]
print(conditions_talker[:10])

# of z-maps:  188
# of conditions:  188
['di1_aN', 'di1_aN', 'di1_aN', 'di1_bN', 'di1_bN', 'di1_bN', 'di1_hN', 'di1_hN', 'di1_hN', 'di1_iN']
unique # of conditions =  (16,)
['di1', 'di1', 'di1', 'di1', 'di1', 'di1', 'di1', 'di1', 'di1', 'di1']
['aN', 'aN', 'aN', 'bN', 'bN', 'bN', 'hN', 'hN', 'hN', 'iN']


### Nilearn `Decoder` accuracies

from https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_glm_decoding.html#build-the-decoding-pipeline

**note: does not generate predictions for each fold, so cannot use for confusion matrix generation**

In [6]:
mask_descrip = 'L-TTG'
mask_fpath = nib.load(os.path.join(mask_dir, 'sub-%s_mask-%s.nii.gz'%(sub_id, mask_descrip)))
decoder=Decoder(estimator='svc', mask=mask_fpath,
                standardize=False,
                screening_percentile=10, 
                cv=5,
               )
decoder.fit(z_maps, conditions)

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/nilearn/_utils/param_validation.py:197: UserWarning: Brain mask is smaller than .5% of the volume human brain. This object is probably not tuned tobe used on such data.
  screening_percentile_ = _adjust_screening_percentile(
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: Con

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/KRS228/software/miniconda3/envs/nilearn_branch_decoder_predictions/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase 

In [7]:
print(decoder.coef_folds_)

{'di1_aN': [array([[ 0.02544593, -0.00309057, -0.00641976,  0.03971621,  0.01385307,
         0.03128774,  0.04175346,  0.0441045 ,  0.03447894, -0.01726892,
        -0.03694411, -0.00055466,  0.02944323, -0.02061298,  0.01148171,
         0.0017398 , -0.01255719, -0.00835567, -0.00439151,  0.00601944,
         0.00563653,  0.0279032 , -0.01983808, -0.00610382,  0.00156417,
        -0.02334416, -0.0149462 ,  0.04946114, -0.01524327, -0.03813508,
        -0.02577114,  0.02043442, -0.02639668,  0.01692574,  0.00269911,
         0.04586845,  0.05939656,  0.02275366,  0.00468709, -0.02443276,
         0.0178985 , -0.03323886,  0.02432043,  0.02446579,  0.05846732,
        -0.00128555, -0.04693218,  0.01957168, -0.02075705, -0.00985598,
        -0.04769621, -0.02362283,  0.00867238, -0.04663726, -0.04333874,
        -0.0117718 , -0.04396395, -0.07477412, -0.02705904, -0.01786704,
         0.0211578 ,  0.05118046, -0.01996839,  0.00999197,  0.01382232,
        -0.02896263,  0.04704383,  0.00

In [11]:
decoder.intercept_folds_raw_

{'di1_aN': [array([-0.9989936]),
  array([-0.99840769]),
  array([-0.23684374]),
  array([-0.99899281]),
  array([-0.91109762]),
  array([-0.99901904]),
  array([-0.99902102]),
  array([-0.99899391]),
  array([-0.91287796]),
  array([-0.99900679])],
 'di1_bN': [array([-0.99897279]),
  array([-0.99838835]),
  array([-0.2365025]),
  array([-0.99898918]),
  array([-0.99897236]),
  array([-0.99898518]),
  array([-0.99899296]),
  array([-0.91032642]),
  array([-0.99900688]),
  array([-0.99897598])],
 'di1_hN': [array([-0.65840109]),
  array([-0.65052253]),
  array([-0.28346532]),
  array([-0.67082386]),
  array([-0.66562093]),
  array([-0.647071]),
  array([-0.67306491]),
  array([-0.6918935]),
  array([-0.69331011]),
  array([-0.66459748])],
 'di1_iN': [array([-0.64087938]),
  array([-0.66825382]),
  array([-0.26456]),
  array([-0.61881477]),
  array([-0.67843255]),
  array([-0.64145379]),
  array([-0.69060051]),
  array([-0.60285257]),
  array([-0.64612506]),
  array([-0.65819209])],
 'di

In [30]:
[np.squeeze(decoder.intercept_folds_raw_[class_index]) for class_index in decoder.classes_]

SyntaxError: invalid syntax (3474127439.py, line 1)

In [14]:
(np.squeeze(decoder.intercept_folds_raw_['di1_aN']))

array([-0.9989936 , -0.99840769, -0.23684374, -0.99899281, -0.91109762,
       -0.99901904, -0.99902102, -0.99899391, -0.91287796, -0.99900679])

In [15]:
decoder.classes_

array(['di1_aN', 'di1_bN', 'di1_hN', 'di1_iN', 'di2_aN', 'di2_bN',
       'di2_hN', 'di2_iN', 'di3_aN', 'di3_bN', 'di3_hN', 'di3_iN',
       'di4_aN', 'di4_bN', 'di4_hN', 'di4_iN'], dtype='<U6')

In [8]:
decoder.intercept_folds_

array(<generator object _BaseDecoder.fit.<locals>.<genexpr> at 0x7f97f9984200>,
      dtype=object)

In [9]:
len(decoder.coef_folds_['di1_aN'][0][0])

380

In [ ]:
decoder.predict_folds()

#### `Decoder` accuracy

In [ ]:
print(decoder.cv_params_)

print('# of CV folds: ', decoder.cv)
classification_accuracy = np.mean(list(decoder.cv_scores_.values()))
chance_level = 1. / len(np.unique(conditions))
print('{} classification accuracy: {:4f} / Chance level: {}'.format(
       sub_id, classification_accuracy, chance_level))

In [ ]:
# Create and save prediction accuracy plot

os.makedirs(os.path.join(trial_map_dir, 'trial_models', 'masked_data'), exist_ok=True)

region_string = mask_descrip #'Auditory cortex'

#acc_plot_fpath = os.path.join(nilearn_sub_dir, 'trial_models', 'masked_data',
#                                '%s_space-%s_roi-%s_trial_decoding_accuracy.png'%(sub_id, 
#                                                                           space_label,
#                                                                           mask_descrip))

from matplotlib import pyplot as plt
plt.figure(figsize=(8,3), dpi=150)
plt.boxplot(list(decoder.cv_scores_.values()));
plt.axhline(y=chance_level, color='r', linewidth=0.5)
plt.title('{} {} SVC accuracy: {:3f} (Chance level: {})'.format(
            sub_id, region_string, classification_accuracy, chance_level))
plt.xlabel('stimulus')
plt.ylabel('accuracy')
plt.xticks(range(1,17), np.unique(conditions), rotation=30);
#plt.xticks(range(1,5), np.unique(conditions_tone));

#plt.savefig(acc_plot_fpath)
#print('saved figure to ', acc_plot_fpath)

In [ ]:
len(decoder.coef_img_)

In [ ]:
decoder.coef_img_['di1_aN']

In [ ]:
'''# save 4-D decoding coefficient images to nifti (3-D x trial type prediction)
decoding_dir = os.path.join(trial_map_dir, 'masked_data', 'decoding')
os.makedirs(decoding_dir, exist_ok=True)
print('saving files to ', decoding_dir)

for ix, decoder_cond in enumerate(decoder.coef_img_):
    decoder_img = decoder.coef_img_[decoder_cond]
    decoder_img_fpath = os.path.join(decoding_dir,
                                     '%s_space-%s_roi-%s_trial_decoding_cond-%s.nii.gz'%(sub_id, 
                                                                               space_label,
                                                                               mask_descrip,
                                                                               decoder_cond))
    nib.save(decoder_img, decoder_img_fpath)'''

In [ ]:
# Extract and save masked timeseries data (for analyzing outside of Decoder method)

masker = NiftiMasker(mask_img=mask_fpath, smoothing_fwhm=None, standardize=False)
masked_data = masker.fit_transform(z_maps)

print(masked_data.shape)

masked_data_fpath = os.path.join(trial_map_dir, 'masked_data',
                                '%s_space-%s_roi-%s_trial_zmaps.csv'%(sub_id, 
                                                                      space_label,
                                                                      mask_descrip))
#np.savetxt(masked_data_fpath, masked_data)
print(masked_data_fpath)

conditions_fpath = os.path.join(trial_map_dir, 'masked_data',
                                '%s_space-%s_roi-%s_trial_conditions.csv'%(sub_id, 
                                                                           space_label,
                                                                           mask_descrip))
#np.savetxt(conditions_fpath, conditions, fmt='%s')
print(conditions_fpath)

In [ ]:
print(z_maps)

### Confusion matrix

In [ ]:
#masked_data_fpath = os.path.join('/bgfs/bchandrasekaran/krs228/data/FLT/',
#                                   'data_bids/derivatives/nilearn/level-1_fwhm-1.50/',
#                                   'sub-FLT01_space-MNI152NLin2009cAsym/trial_models/masked_data/',
#                                   'FLT01_roi-IC_trial_zmaps.csv')
masked_data_fpath = os.path.join(trial_map_dir, 'masked_data/',
                                 'FLT01_space-T1w_roi-actx_trial_zmaps.csv')

masked_data = np.genfromtxt(masked_data_fpath)

In [ ]:
n_train = round(len(z_maps)*0.75)
n_test = len(z_maps) - n_train

In [ ]:
# first, run a new classifier with a separate training and test set
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn import svm

In [ ]:
cv = KFold(n_splits=10)

clf = svm.LinearSVC()

In [ ]:
# run SVM with cross-validation and create confusion matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf, masked_data, conditions, cv=10)
conf_mat = confusion_matrix(conditions, y_pred)

In [ ]:
#print('input data file: ', masked_data_fpath)
ConfusionMatrixDisplay.from_predictions(conditions, y_pred, 
                                        cmap='viridis', colorbar=False, include_values=False)

In [ ]:
# SVM with no cross validation
X_train, X_test, y_train, y_test = train_test_split(masked_data, conditions)
clf.fit(X_train, y_train)

ConfusionMatrixDisplay.from_estimator(clf, X_test, y_test, cmap='viridis_r', colorbar=False)
plt.show()

#### TEST: confusion matrix using decoder (then replaced by SVM) 

In [ ]:
cv = KFold(n_splits=10)
fold = 0
prediction = []
test_conds = []
for train, test in cv.split(conditions):
    fold += 1
    subdecode=svm.LinearSVC()
    
    # fit on the training set
    print('# of training images: ', n_train)
    print('# of testing images:  ', n_test)

    print('fitting the training data')
    subdecode.fit(masked_data[train, :], np.array(conditions)[train])
    
    # test
    print('predicting the test images')
    y_pred = subdecode.predict(masked_data[test, :])
    #print(y_pred)
    prediction.append(y_pred)
    
    #print(np.array(conditions)[test])
    test_conds.append(np.array(conditions)[test])

In [ ]:
test_conds

In [ ]:
for fx in range(len(prediction)):
    print(prediction[fx]==test_conds[fx])

In [ ]:
import seaborn as sns
plt.figure(figsize=(5,4),dpi=100)
confusion_mat = confusion_matrix(y_pred, conditions[n_train:], normalize='all')
ax = sns.heatmap(confusion_mat, 
                 cmap='hot_r',
                )

ax.set_xticks(range(len(np.unique(conditions))))
ax.set_yticks(range(len(np.unique(conditions))))
ax.set_xticklabels(np.unique(conditions), rotation=45)
ax.set_yticklabels(np.unique(conditions), rotation=45)

#ax.set_xticklabels(range(1,5))
#ax.set_yticklabels(range(1,5))

ax.set_xlabel('predicted')
ax.set_ylabel('true value')

plt.show()
print(confusion_mat)

#### Plot decoder maps

In [ ]:
# T1w space (ACtx)
t1w_fpath = 

# plot
for stim in np.unique(conditions): #stim_list:
    decoder_img = decoder.coef_img_[stim]
    plotting.plot_stat_map(decoder_img, bg_img=t1w_fpath, colorbar=True, 
                           title=stim,
                           cut_coords=[-40, 40, 0]
                           #axes=axes[0],
                           #display_mode='x', cut_coords=6
                           )

plotting.show()


In [ ]:
# MNI space (IC)
t1w_mni_fpath = os.path.join('/bgfs/bchandrasekaran/krs228/data/FLT/',
                             'derivatives', 'fmriprep_2022.03.22',
                             'sub-FLT01/anat',
                             'sub-FLT01_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz')

# plot
for stim in np.unique(conditions): #stim_list:
    decoder_img = decoder.coef_img_[stim]
    plotting.plot_stat_map(decoder_img, bg_img=t1w_mni_fpath, colorbar=True, 
                           title=stim,
                           cut_coords=[1, -35, -9]
                           #axes=axes[0],
                           #display_mode='x', cut_coords=6
                           )

plotting.show()
